spring:
  datasource:
    url: jdbc:mysql://${DB_HOST_TEST:localhost}:3306/lbytech_backend_new?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME_TEST:root}
    password: ${DB_PASSWORD_TEST:123456}
  data:
    redis:
      host: ${REDIS_HOST_TEST:localhost}
      port: ${REDIS_PORT_TEST:6379}
      password: ${REDIS_PASSWORD_TEST:1234}
      database: 1